### ISSUE TITLE
Maildir plugin documentation

### ISSUE THREAD

**Issue by BoniLindsley** [icgood/pymap#123]
The project README seems to suggest, at least to me, that the maildir plugin reads plaintext passwords from `users.txt`. I think it actually wants hashes instead, generated from, for example

```python
import passlib.context
print(passlib.context.CryptContext(schemes=["sha512_crypt"]).hash("Tr0ub4dor&3"))
```

And, as far as I can tell, the maildir plugin is incompatible with the admin service.

These points might need to be clarified in the README.

**Comment by htgoebel** [comment]
I was bugged by this, too. I digged deeply into the code and found that one *may* pass some config-file using `--passlib-cfg`. Anyhow, > found no documentation about this (until I discovered your workaround).

**Comment by htgoebel** [comment]
To be frank: it's a shame this project spends time on switching build-system, but does not solve this trivial issue within 1 1/2 years.

**Comment by icgood** [comment]
Fair feedback, but to copy what the former-BDFL once wrote back to me: ["Submit a patch"](https://twitter.com/gvanrossum/status/550138988883746816) he said, and so I [did](https://github.com/python/cpython/commit/6217864fe5f6855f59d608733ce83fd4466e1b8c).

I derive no personal value from this project, I don't accept tips or donations, it's purely for fun and to stay sharp. Apologies for the time spent due to doc errors, they were correct at one point, and may be again someday.

**Comment by icgood** [comment]
A little more context, I'd like for the README to still be correct. Rather than updating the README, I want to fix the behavior so that cleartext passwords are still the default for the maildir plugin. Documenting the current workarounds of using passlib configs is not super appealing to me, if anything maybe just a note in the README linking to this issue.

The end goal is to implement the admin plugin support for maildir so that you can use `pymap-admin` commands to manage the users file, then it would not matter as much if the file stores hashes. But implementing admin support for maildir will take time, so for now I'd rather just figure out how to make it support cleartext again.

**Comment by htgoebel** [comment]
I appreciate your voluntary work and want to apologize for my harsh words.

I share you idea of making cleartext passwords work. Sadly the code is too complex for me to understand what is going in there and to submit a patch.

**Comment by icgood** [comment]
No problem at all. I've created issues #146 and #147 that I think cover the asks of this issue, so I'm closing this one.
