### ISSUE TITLE
Maildir colon option for info delimiter

### ISSUE THREAD

**Issue by BoniLindsley** [icgood/pymap#124]
Mails created by the maildir plugin use colons in their filenames. For example, `1637427835.M325307P10914Q1.localhost:2,S`. However, the colon character is reserved in Windows paths.

Are you open to adding a `--colon` option or similar as a customisation point?

**Comment by icgood** [comment]
Good question, I think the "note" about this in the Python docs should work since pymap uses these modules under the hood:

https://docs.python.org/3/library/mailbox.html#mailbox.Maildir

Specifically this:

```python
import mailbox
mailbox.Maildir.colon = '!'
```

However that would require basically re-creating the `pymap` command, so a command line `--colon` would make a lot of sense.
