### ISSUE TITLE
Stream body instead of loading into memory

### ISSUE THREAD

**Issue by Skorpeo** [icgood/pymap#59]
Hi,

Nice library!  I admit I don't follow everything but if I am not mistaken it seems like messages are fully loaded into memory both when being received and sent.  If that is the case I would be very interested in helping fix this (i.e. streaming/chunking body) but not sure how much refactoring it would take and your assistance would really help. 

Couple of areas I saw:

https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/imap/__init__.py#L169

Here it looks like everything is read in one go, wasn't sure if (at least) for append commands the reading of the body can be streamed/chunked in the command itself.  This would require pushing the reading and parsing after the command instruction down to the "command function itself"

https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/backend/session.py#L188

This seems to load all messages into memory.  I tried a intermediate fix by using a generator, i.e. 
```

ret = ((seq, msg) async for seq, msg
               in mbx.find(sequence_set, selected, req))
        if not selected.readonly and any(attr.set_seen for attr in attributes):
            seen_set = frozenset([Seen])
            await mbx.update_flags((msg async for _, msg in ret),
                                   seen_set, FlagOp.ADD)
```

and changing:
https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/imap/state.py#L271

to:
`async for msg_seq, msg in messages:`

but this generates some other errors in tests, plus it seems that this would still load each individual messages fully and eventually load them all into memory anyway before sending.

I spent a little time but I wanted to get your input and thoughts first.

**Comment by icgood** [comment]
Yeah, true, re: loading all messages into memory. Although I really don't think we'll be able to avoid loading every message's _metadata_ into memory at once (UID + flags), since IMAP has to report state changes since the last command. That's been by far the hardest problem to solve thus far, and gets kinda ugly:

https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/selected.py#L400-L429

However, that being said, the real memory killer is the message contents. And luckily, those are only exposed in FETCH.

For that few things come to mind:

* The mechanisms for sending untagged responses will need to be changed, e.g.:

https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/imap/state.py#L276

I think the IMAPConnection object would need to provide some kind of async hook for the IMAPState methods to immediately write an untagged response.

* The methods and logic around getting message contents in [interfaces/message.py](https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/interfaces/message.py) would need to be changed.

For this, I'm envisioning the Message interface having something like this instead:

```python
@abstractmethod
def content(self) -> AsyncContextManager[MessageContent]:
    ...
```

Then, as the `do_fetch` method is streaming through adding untagged responses, it can go fetch the message contents right there, and only keep it in-memory long enough to write it out.

**Comment by Skorpeo** [comment]
Well the append command also reads the whole message into memory before saving right?  Agree with the metadata.  

Essentially I would propose reading and writing headers separately from message contents (also handle mime parts separately).  Possibly reading headers and then passing along the socket to the backend which could decide how to read it.  Something along the lines of: (I believe in imap one may know the size of content so while True could be replaced with a for loop).


```
with open(filename, 'wb') as f:
    while True:
        chunk = await reader.read(chunk_size)
        if not chunk:
            break
        f.write(chunk)
```
it could also still opt to read everything such as `await reader.read() or await reader.read(size)`

Additionally it could also opt for the new `loop.sock_recv_into()` facility.

On the fetch side similarly one could send headers separately and pass the message contents as an object separately to the response handler which could be a filehandle, or a bytearray, or a async generator, and depending on type client could stream it, could be something like:

```
with open(filename, 'rb') as f:
  while True:
      chunk = f.read(chunksize)
      if not chunk:
          break
      writer.write(chunk)
      await writer.drain()
```

or alternatively use   `loop.sendfile()`

so i think 
https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/imap/__init__.py#L169

needs to be modified for append command.  I think cleanest would be for each command to handle its own reading after the command type has been identified, one could then still have all of the commands have common "read remaining method" and use a separate method for append command that reads headers and then does contents separately.  Alternatively, have a "if append" type test and then handle that separately (albeit no that clean).

My understanding is that headers are line delimited so if I'm correct this can be essentially parsed using readline()?

Also, saving/streaming mime parts separately as opposed to whole body?

Thoughts? I will further read into your comments but need some time to digest.

**Comment by Skorpeo** [comment]
ok based on your response and cursory review, I think the  interfaces/message.py methods can stay but they would have to be turned into async methods, specifically get_body(), so it would become async def get_body(), (another idea would be to have a body attribute as opposed to method?) Similar would go for MessageAttributes in https://github.com/icgood/pymap/blob/c20247652fd262b9ac4f848857e1803288e5ada3/pymap/fetch.py#L44

and anything that uses those would be modified to take this into account as well as the actual writing of the response.

I think probably only get_body, get_data, and get_partial needs this but perhaps might as well async all of them in case it comes in handy in the future? Underlying logic could still be synchronous even if awaited.   I think this is going to need a lot of surgery, if you are on board (also see above comments) I think I can do it however I would need help on tests,  would you be willing to rewrite those? 

I would start with fetch, but would later like to work on append also but I thing append is going to be a little trickier, but I think I have a gameplan.

**Comment by icgood** [comment]
Regarding append, the [MULTIAPPEND](https://tools.ietf.org/html/rfc3502) extension is something to keep in mind. I actually believe the append work would coincide will with my goal of implementing RFC 8474 in #60, as I am working towards the goal of de-duping message content using the `EMAILID` value. I think it would work for backends to provide an async method that consumes data of a certain length from a socket and returns an `EMAILID` value which is assigned to the message (instead of content) on save. If the message is not saved, the content is garbage collected on the next [CHECK](https://tools.ietf.org/html/rfc3501#section-6.4.1) (or similar).

**Comment by icgood** [comment]
I think you're plans for modifying `MessageInterface` and `MessageAttributes` are sound, I'm happy to help with tests once you get there. Check out the tests in `test_fetch.py` and feel free to adapt new ones as necessary.

**Comment by Skorpeo** [comment]
hey, i know this is going to sound shitty, but I spent a few hours and started working on the fetch but it seems like there's too many changes to make and there's also a lot of layers and abstractions that I'm not privy too which slowed me down and made it a little cumbersome, in part because of my lack of familiarity with imap etc.  I think this is just going to take me too much time that I don't have right now :/.

**Comment by icgood** [comment]
No problem. IMAP is an obnoxiously complex protocol, and (for better or worse) I wanted to stay as close to RFC compatibility as possible. That means there are lower-level APIs and interfaces and higher-level ones, and unfortunately the changes you discussed reside in the lower-level APIs.

I've merged several PRs to address things we've talked about. I believe, at this point, there are no longer moments where more than one message is kept entirely in memory. I've also worked in optimizations for de-duping message content so that e.g. ``COPY`` no longer copies the message content, only its in-folder metadata. That will make it less costly for UIs that want to apply labels to messages, rather than using a folder structure. More work to do there though, I think.

In regards to streaming message data to the backend, rather than loading it in-memory first, I'm shelving that idea for now until there is a backend that would benefit from it. The maildir backend _could_ benefit, but it would require functionality that the built-in [`Maildir`](https://docs.python.org/3/library/mailbox.html#maildir) doesn't provide.
